# Generated by Django 3.0.3 on 2021-03-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudioApp', '0003_creative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='', upload_to='wedding')),
            ],
        ),
        migrations.AlterField(
            model_name='creative',
            name='photo',
            field=models.ImageField(default='', upload_to='creative'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='shots'),
        ),
    ]
