# Generated by Django 3.0.3 on 2021-03-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudioApp', '0004_auto_20210321_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framephoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framephoto', models.ImageField(default='', upload_to='framephoto')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.ImageField(default='', upload_to='passport')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='', upload_to='photo')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.ImageField(default='', upload_to='portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Shots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shots', models.ImageField(default='', upload_to='shots')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RenameField(
            model_name='creative',
            old_name='photo',
            new_name='creative',
        ),
        migrations.RenameField(
            model_name='wedding',
            old_name='pic',
            new_name='Wedding',
        ),
    ]
