# Generated by Django 3.0.3 on 2021-03-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudioApp', '0005_auto_20210322_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventural', models.ImageField(default='', upload_to='adventural')),
            ],
        ),
        migrations.CreateModel(
            name='Agricultural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agricultural', models.ImageField(default='', upload_to='agricultural')),
            ],
        ),
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Birthday', models.ImageField(default='', upload_to='birthday')),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone', models.ImageField(default='', upload_to='drone')),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival', models.ImageField(default='', upload_to='festival')),
            ],
        ),
        migrations.CreateModel(
            name='Newborn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newborn', models.ImageField(default='', upload_to='newborn')),
            ],
        ),
        migrations.DeleteModel(
            name='Framephoto',
        ),
        migrations.DeleteModel(
            name='Passport',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
