# Generated by Django 3.0.3 on 2021-04-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudioApp', '0009_auto_20210329_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('item1', models.CharField(max_length=500)),
                ('item2', models.CharField(max_length=500)),
                ('item3', models.CharField(max_length=500)),
                ('item4', models.CharField(max_length=500)),
                ('item5', models.CharField(max_length=500)),
            ],
        ),
    ]
