# Generated by Django 3.0.3 on 2021-04-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudioApp', '0011_remove_booking_item5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fashion', models.ImageField(default='', upload_to='fashion')),
            ],
        ),
        migrations.DeleteModel(
            name='Drone',
        ),
    ]
