# Generated by Django 3.0.3 on 2021-04-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudioApp', '0012_auto_20210401_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('item1', models.CharField(max_length=500)),
                ('item2', models.CharField(max_length=500)),
                ('item3', models.CharField(max_length=500)),
                ('item4', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='item1',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='item2',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='item3',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='item4',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(default=2, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=5, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.CharField(default=8, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default=7, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
