# Generated by Django 3.0.3 on 2021-04-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudioApp', '0013_auto_20210403_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='pincode',
        ),
        migrations.AddField(
            model_name='services',
            name='imagetype',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
