# Generated by Django 3.0.3 on 2021-05-02 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('StudioApp', '0014_auto_20210404_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='Birthday',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='wedding',
            old_name='Wedding',
            new_name='wedding',
        ),
        migrations.RemoveField(
            model_name='services',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='services',
            name='lname',
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='imagequantity',
            field=models.CharField(default=8, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='imagesize',
            field=models.CharField(default=datetime.datetime(2021, 5, 2, 11, 26, 48, 707196, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='name',
            field=models.CharField(default=datetime.datetime(2021, 5, 2, 11, 31, 35, 497698, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='imagetype',
            field=models.CharField(max_length=200),
        ),
    ]
